# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fa2455b12e19643063d4a289d47ced7902fa745a7b3d7d9f82a5b657d91889acf1db557ff396889506b0b0df54aeb2f0debaf2ca9a209f4ac9b0a254fdafd7f

test:
  secret_key_base: 51e60ed3edbeb87aff5301b7645eda51a940382bbdc1298abee672ca0e043e77376ba48d7e9c1a02116adebe2758517612ca26906b31c4db0edd73720d806907

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
